version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
    - checkout
    - setup_remote_docker
    - run:
name: Build Docker Image
command: docker build -t
  marcolinodocker/restApi:latest .
  - run:
name: Push to Docker Hub
command: |
  echo "$DOCKERHUB_PASS" | docker login -u
  "$DOCKERHUB_USERNAME" --password-stdin
  docker push marcolinodocker/restApi:latest
workflows:
version: 2
build_and_push:
jobs:
  - build